#!/usr/bin/env bash
# Bash script that will display information about subdomains.

function domain_check {
    domain_names=("www" "lb-01" "web-01" "web-02")

    for i in "${domain_names[@]}"; do
        dig +short -t A "${i}"."$1" | awk -v var="$i" 'NR==1 {printf "The subdomain %s is a %s record and points to %s\n", var, $1, $0}'
    done
}

function subdomain_check {
    dig +short -t A "${2}"."$1" | awk -v var="$2" 'NR==1 {printf "The subdomain %s is a %s record and points to %s\n", var, $1, $0}'
}

if [ $# -lt 1 ]; then
    printf "*** Provide domain name ***\n"
elif [ $# -eq 1 ]; then
    domain_check "$1"
else
    subdomain_check "$1" "$2"
fi

